/** Illustrative games for the canvas preview — real codes so the box-art and
 *  grid previews pull real covers from the bundled art library. Enough to fill
 *  a tall list or a full grid; `artInfo` region-fallback handles the code. */
export const SAMPLE_GAMES: { title: string; code: string }[] = [
  { title: 'Super Mario 64', code: 'NSME' },
  { title: 'The Legend of Zelda: Ocarina of Time', code: 'CZLE' },
  { title: "The Legend of Zelda: Majora's Mask", code: 'NZSE' },
  { title: 'GoldenEye 007', code: 'NGEE' },
  { title: 'Mario Kart 64', code: 'NKTE' },
  { title: 'Banjo-Kazooie', code: 'NBKE' },
  { title: 'Banjo-Tooie', code: 'NB7E' },
  { title: 'Perfect Dark', code: 'NPDE' },
  { title: 'Star Fox 64', code: 'NFXE' },
  { title: 'Paper Mario', code: 'NMQE' },
  { title: 'Diddy Kong Racing', code: 'NDYE' },
  { title: 'Wave Race 64', code: 'NWRE' },
  { title: 'Kirby 64: The Crystal Shards', code: 'NK4E' },
  { title: 'Pilotwings 64', code: 'NPWE' },
  { title: 'Donkey Kong 64', code: 'NDOE' },
  { title: 'Super Smash Bros.', code: 'NALE' },
  { title: 'Mario Party', code: 'NMWE' },
  { title: 'Mario Party 2', code: 'NMVE' },
  { title: "Yoshi's Story", code: 'NYSE' },
  { title: '1080 Snowboarding', code: 'NEAE' },
  { title: 'F-Zero X', code: 'NFZE' },
  { title: "Conker's Bad Fur Day", code: 'NFUE' },
  { title: 'Jet Force Gemini', code: 'NJFE' },
  { title: 'Star Wars: Rogue Squadron', code: 'NRSE' },
  { title: 'Turok 2: Seeds of Evil', code: 'NRWE' },
  { title: 'Beetle Adventure Racing', code: 'NBHE' },
  { title: 'Blast Corps', code: 'NBCE' },
  { title: 'Body Harvest', code: 'NBVE' },
  { title: 'Excitebike 64', code: 'NMXE' },
  { title: 'Mario Golf', code: 'NADE' },
  { title: 'Mario Tennis', code: 'NASE' },
  { title: 'Pokémon Snap', code: 'NPFE' },
  { title: 'Pokémon Stadium', code: 'NPOE' },
  { title: 'Star Wars: Episode I Racer', code: 'NEPE' },
  { title: 'WWF No Mercy', code: 'NW2E' },
  { title: 'Mystical Ninja Starring Goemon', code: 'NGSE' },
];
